#ifndef HTTP_CONSTANTS_H
#define HTTP_CONSTANTS_H


#define HTTP_VERB_GET		"GET"
#define	HTTP_VERB_POST		"POST"
#define	HTTP_VERB_HEAD		"HEAD"
#define	HTTP_VERB_CONNECT	"CONNECT"

#define HTTP_OK						200
#define HTTP_METHOD_NOT_ALLOWED		405
#define HTTP_VERSION_NOT_SUPPORTED	505
#define HTTP_EXPECTATION_FAILED		417

#define HTTP_VERSION_1_0		"1.0"
#define HTTP_VERSION_1_1		"1.1"


#define HTTP_HEADER_CONNECTION		"Connection"
#define HTTP_HEADER_DATE			"Date"
#define HTTP_HEADER_CONTENT_LENGTH	"Content-Length"
#define HTTP_HEADER_HOST			"Host"

#define HTTP_DEFAULT_VERSION					HTTP_VERSION_1_0
#define HTTP_DEFAULT_URI						"/"
#define HTTP_DEFAULT_URI_MAX_LENGTH				8000
#define HTTP_DEFAULT_REQUEST_LINE_MAX_LENGTH	8190
#define HTTP_DEFAULT_REQUEST_MAX_FIELDS			100
#define HTTP_DEFAULT_CONNECTION					"close"
#define	HTTP_DEFAULT_HOST_MAX_LENGTH			512

#endif